apiVersion: platform.kratix.io/v1alpha1
kind: Promise
metadata:
  name: unleash-templated-promise
  annotations:
    chart: unleash/unleash
    config.kubernetes.io/function: |
      exec:
        path: ./worker-cluster-resource-injector
spec:
  # injected via kustomization
  # workerClusterResources:
  xaasRequestPipeline:
  - syntasso/unleash-templated-request-pipeline:dev
  xaasCrd:
    apiVersion: apiextensions.k8s.io/v1
    kind: CustomResourceDefinition
    metadata:
      name: unleash-templated.promise.example.com
    spec:
      group: promise.example.com
      scope: Namespaced
      names:
        plural: unleash-templated
        singular: unleash-templated
        kind: unleash-templated
      versions:
      - name: v1
        served: true
        storage: true
        schema:
          openAPIV3Schema:
            type: object
            properties:
              spec:
                type: object
                properties:
                  service-port:
                    type: string
